[project]
name = "paillier-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "matplotlib>=3.10.9",
    "phe>=1.5.0",
    "pydantic>=2.13.4",
    "pytest>=9.0.3",
    "streamlit>=1.57.0",
    "uvicorn>=0.47.0",
]
